[meta]
name = "EzToolbox"
author = "Ezio"
category = "Utilities"
version = "1.0.0"
siteid = 396

[script]
optional_dependencies = [ "NadeoServices" ]
shared_exports = [ "src/Game.as", "src/Http.as" ]
