[meta]
name = "EzToolbox"
author = "Ezio"
category = "Utilities"
version = "1.0.0"
siteid = 396

[script]
optional_dependencies = [ "NadeoServices", "MLHook" ]
export_dependencies = [ "NadeoServices", "MLHook" ]

module = "Ez"
shared_exports = [ "src/Export/Shared/Exports.as", "src/Export/Shared/Json.as" ]
